config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods

   root 'foods#index'

end

app/models/food.rb
class Food < ActiveRecord::Base
		
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :find_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.all.order("created_at DESC")
  end

  def show
  
  end

  def new
  	@food = Food.new
  end

  def create
  	@food = Food.new(food_params)
    if @food.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @food.destroy
    redirect_to food_path
  end

  def edit
  end

  def update
    if @food.update(food_params)
      redirect_to food_path(@food)
    else
      render 'edit'
    end
  end

  private 
  
  	def food_params
  		params.require(:food).permit(:title, :description, :price)
  	end	

    def find_food
       @food = Food.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= simple_form_for @food do |f|%>
<%= f.input :title, label: "Food Title" %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.button :submit %>


<% end %>

app/views/foods/create.html.erb
<h1>Foods#create</h1>
<p>Find me in app/views/foods/create.html.erb</p>

app/views/foods/delete.html.erb
<h1>Foods#delete</h1>
<p>Find me in app/views/foods/delete.html.erb</p>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>
<%= render 'form' %>

app/views/foods/index.html.erb
<% @foods.each do |food| %>
<h2><%=  link_to food.title, food_path(food) %></h2>
<% end %>

<%= link_to "Add Food", new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

app/views/foods/show.html.erb
<h2> <%= @food.title %></h2>
<p><%= @food.description %></p>
<h2> <%= @food.price %></h2>

<%= link_to "Back", root_path %>
<%=link_to "Edit", edit_food_path(@food)  %>

<%=link_to "Delete", food_path(@food), method: :delete, data: {confirm: "Are you sure?"}  %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ResturantApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
	<div class="container">

		<div class="navbar-header">
			<%= link_to "Food Review", root_path, class: "navbar-brand" %>
		</div>

		<ul class="nav navbar-nav">
			<li><%= link_to "Sign Up", new_user_registration_path %></li>
			<% if user_signed_in? %>
				<li><%= link_to "Sign Out", destroy_users_session_path, method:delete%></li>
			<% else %>
				<li><%= link_to "Log In", new_user_session_path %></li>

			<% end %>
		</ul>
	</div>
	
</nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>